### PR TITLE
Podval uzgardi

### PR DESCRIPTION
**Pull request by Arti5st**
futer rangi uzgardi

### CODE REVIEW

**Comment by Arti5st** [comment]
pbolsa

**Comment by skywoker007** [comment]
bo`ladi versatka kk

**Comment by Arti5st** [comment]
@skywoker007 aytganda versatka qildim

**Comment by skywoker007** [comment]
ok

**Review by skywoker007 — CHANGES_REQUESTED** [review]
change color

**Comment by Arti5st** [comment]
color changed

**Comment by skywoker007** [comment]
i see all ok

**Review by skywoker007 — APPROVED** [review]

**Pull request merged**
